.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2021 Glenn de Haan <glenn@dehaan.cloud>,
.TH G-SSL-COMP 1 "May 13 2021"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
g-ssl-comp \- utility for comparing SSL certificate sets
.SH SYNOPSIS
.B g-ssl-comp
.RI [ options ] " directory"
.SH DESCRIPTION
An SSL comparator that checks if the entire set (private key, certificate request and certificate) belongs to each other
.PP
.SH OPTIONS
This programs follows the usual GNU command line syntax.
A summary of options is included below.
.TP
.B \-h
Show summary of options.
