.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2021 Glenn de Haan <glenn@dehaan.cloud>,
.TH G-PASSWORD-GEN 1 "May 12 2021"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
g-password-gen \- utility for generating passwords
.SH SYNOPSIS
.B g-password-gen
.RI [ options ]
.SH DESCRIPTION
A simple password generator
.PP
.SH OPTIONS
This programs follows the usual GNU command line syntax.
A summary of options is included below.
.TP
.B \-h
Show summary of options.
.TP
.B \-n
Non-interactive password generation with default settings.
