#!/bin/bash

################################################################################
# Globals                                                                      #
################################################################################
COLOR_RED="\033[91m"
COLOR_GREEN="\033[92m"
COLOR_YELLOW="\033[93m"
COLOR_CYAN="\033[96m"
COLOR_RESET="\033[m"

################################################################################
# Help                                                                         #
################################################################################
Help()
{
   # Display Help
   echo "Usage: g-inet-test [options]"
   echo "A simple utility that tests if you are connected to the internet"
   echo
   echo "Options:"
   echo "  -h     Print this help"
   echo
}

################################################################################
# Process the input options                                                    #
################################################################################
# Get the options
while getopts ":h" option; do
   case $option in
      h) # Display help
         Help
         exit;;
     \?) # Incorrect option
         echo "Error: Invalid option"
         exit;;
   esac
done

################################################################################
# Print banner                                                                 #
################################################################################
echo "   ______    ______            __    ";
echo "  / ____/   /_  __/___  ____  / /____";
echo " / / ________/ / / __ \/ __ \/ / ___/";
echo "/ /_/ /_____/ / / /_/ / /_/ / (__  ) ";
echo "\____/     /_/  \____/\____/_/____/  ";
echo "                                     ";

echo "Internet Test (https://github.com/glenndehaan/bash-utils)"
echo

################################################################################
# Run tests                                                                    #
################################################################################
NAME_GOOGLE=google.com
NAME_CLOUDFLARE=cloudflare.com

IP_GOOGLE=8.8.8.8
IP_CLOUDFLARE=1.1.1.1

INTERFACE=$(ip route | awk '/default/ { print $5 }')
GATEWAY=$(ip route | awk '/default/ { print $3 }')

echo -e "${COLOR_GREEN}Running tests... (this can take up to 1 minute to complete)${COLOR_RESET}"
echo ""

if ping -q -c 5 "$NAME_GOOGLE" >/dev/null 2>&1 || ping -q -c 5 "$NAME_CLOUDFLARE" >/dev/null 2>&1; then
    echo -e "${COLOR_GREEN}You are connected to the internet via interface \"$INTERFACE\".${COLOR_RESET}"
    exit 0
else
    if ping -q -c 5 "$IP_GOOGLE" >/dev/null 2>&1 || ping -q -c 5 "$IP_CLOUDFLARE" >/dev/null 2>&1; then
        echo -e "${COLOR_CYAN}Your DNS server(s) is/are not responding. Check your configuration locally or on your DHCP Server.${COLOR_RESET}"
        exit 1
    else
        if ping -q -c 5 "$GATEWAY" >/dev/null 2>&1; then
            echo -e "${COLOR_YELLOW}The problem seems to be on the ISP side. Please contact your ISP or try restarting your modem/router.${COLOR_RESET}"
            exit 1
        else
            echo -e "${COLOR_RED}Can't connect to your modem/router. Please check your network cable or wireless signal. Also check if your modem/router is turned on.${COLOR_RESET}"
            exit 1
        fi
    fi
fi
