.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2021 Glenn de Haan <glenn@dehaan.cloud>,
.TH G-SYS-INFO 1 "May 18 2021"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
g-sys-info \- utility for comparing SSL certificate sets
.SH SYNOPSIS
.B g-sys-info
.RI [ options ]
.SH DESCRIPTION
A simple System info reporting tool
.PP
.SH OPTIONS
This programs follows the usual GNU command line syntax.
A summary of options is included below.
.TP
.B \-h
Show summary of options.
