.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2021 Glenn de Haan <glenn@dehaan.cloud>,
.TH G-SSL-INFO 1 "Jun 14 2021"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
g-ssl-info \- utility that provides basic info about an SSL bundle
.SH SYNOPSIS
.B g-ssl-info
.RI [ options ] " directory"
.SH DESCRIPTION
A simple SSL utility that provides basic info about an SSL bundle
.PP
.SH OPTIONS
This programs follows the usual GNU command line syntax.
A summary of options is included below.
.TP
.B \-h
Show summary of options.
