.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2021 Glenn de Haan <glenn@dehaan.cloud>,
.TH G-NGINX-DYNAMIC-WHITELISTS 1 "Oct 6 2021"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
g-nginx-dynamic-whitelists \- utility for generating nginx ip whitelists
.SH SYNOPSIS
.B g-nginx-dynamic-whitelists
.RI [ options ]
.SH DESCRIPTION
An Nginx Dynamic IP Whitelists Generator
This system pulls IP information from a global TCP server
.PP
.SH OPTIONS
This programs follows the usual GNU command line syntax.
A summary of options is included below.
.TP
.B \-h
Show summary of options.
